version: '3.8'

services:
  inventory-service:
    build:
      context: ../inventory-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - BACKEND_INVENTORY_SERVICE_URL=http://inventory-service:8081
    depends_on:
      - inventory-service
    networks:
      - microservices-network

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_INVENTORY_SERVICE_URL=http://inventory-service:8081
      - BACKEND_ORDER_SERVICE_URL=http://order-service:8082
      - BACKEND_USER_SERVICE_URL=http://user-service:8083
    depends_on:
      - inventory-service
      - order-service
      - user-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge